version: "3.8"

services:
  runner:
    build: .
    container_name: github-runner
    env_file:
      - .env
    environment:
      RUNNER_NAME: "my-runner"
      RUNNER_REPOSITORY_URL: ${RUNNER_REPOSITORY_URL}
      #RUNNER_ORGANIZATION_URL: ${RUNNER_ORGANIZATION_URL}
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./_work:/home/runner/_work
    restart: unless-stopped