name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main
  release:
    types:
      - created
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Para mejor manejo de metadatos de git

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3  # Requerido para builds multi-arquitectura

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Habilita soporte multi-plataforma

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/gitlab-runner
          tags: |
            type=raw,value=latest  # Siempre etiqueta como latest
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}  # Etiqueta versión completa (ej. v1.0.0)
            type=semver,pattern={{major}}.{{minor}}  # Etiqueta mayor.minor (ej. v1.0)
            type=sha  # SHA del commit

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile  # Asegura que use el Dockerfile correcto
          platforms: linux/amd64,linux/arm64  # Soporte para múltiples arquitecturas
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gitlab-runner:latest
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/gitlab-runner:cache
          cache-to: type=inline

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/gitlab-runner
          readme-filepath: ./README.md
