name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main
  release:
    types:
      - created
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # For better git metadata handling

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3  # Required for multi-platform builds

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Enables multi-platform support

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/gitlab-runner
          tags: |
            type=ref,event=branch  # Branch-based tag
            type=ref,event=pr      # Pull request tag
            type=semver,pattern={{version}}  # Full semantic version
            type=semver,pattern={{major}}.{{minor}}  # Major.minor version
            type=sha  # Git commit SHA tag

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile  # Specify your Dockerfile location
          platforms: linux/amd64,linux/arm64  # Multi-platform support
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/gitlab-runner:cache
          cache-to: type=inline

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/gitlab-runner
          readme-filepath: ./README.md